#ifndef MYPIHK_H
#define MYPIHK_H
enum  FILEPARTS {DATUM, NAME, NUMMER,FACHRICHTUNG,AUSSCHUSS,LEER};
enum  FILEPARTSDELIM {MINUS,PLUS,PUNKT,UNTERSTRICH,EMPTY};
enum  FILESPACECHAR {UNDERSCORE,ADD,SUB,ORIGINAL,DELETE};
enum  QUALITY {SHORT,LONG};
#endif // MYPIHK_H
