#ifndef MYPIHK_H
#define MYPIHK_H
enum  class FILEPARTS {DATUM, NAME, NUMMER,FACHRICHTUNG,AUSSCHUSS,LEER};
enum  class FILEPARTSDELIM {MINUS,PLUS,PUNKT,UNTERSTRICH,EMPTY};
enum  class FILESPACECHAR {UNDERSCORE,ADD,SUB,ORIGINAL,DELETE};
enum  class QUALITY {SHORT,LONG};
#endif // MYPIHK_H
